# This file was generated by GoReleaser. DO NOT EDIT.
cask "cbx-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3bfd43d42a78ce42e33452770d4708a568ca25d2c53a07779c89d94956462b98"
      url "https://github.com/cloudbooster-io/cbx-cli/releases/download/v#{version}/cbx-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "db6d3ee24b6ba7f6e5f2ce9182ead19a3b235b4664521f6296c5ceb610febcab"
      url "https://github.com/cloudbooster-io/cbx-cli/releases/download/v#{version}/cbx-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa5f1cd0ccd40e679bc26b946910722501988501af374ff8fef10b20720d14e7"
      url "https://github.com/cloudbooster-io/cbx-cli/releases/download/v#{version}/cbx-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "90b25c073384c2d46a642999d3349ec9946a79c0637fe64b6e245fddcde8d335"
      url "https://github.com/cloudbooster-io/cbx-cli/releases/download/v#{version}/cbx-cli_Linux_arm64.tar.gz"
    end
  end

  name "cbx-cli"
  desc "CloudBooster CLI — plan and audit your cloud infrastructure."
  homepage "https://github.com/cloudbooster-io/cbx-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cbx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cbx"]
    end
  end

  # No zap stanza required

end
